# Generated by Django 4.0.4 on 2022-05-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro'},
        ),
    ]
